services:
  postgres:
    image: postgres:16
    container_name: sms_saas_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: motdepasse
      POSTGRES_DB: sms_saas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: sms_saas_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: